name: GitHub-Runner

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/github-runner.yml'
      - 'deploy/terraform/github-runner/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/github-runner.yml'
      - 'deploy/terraform/github-runner/**'

env:
  ARTIFACT_NAME: "github-runner"

permissions:
  id-token: write
  contents: read

jobs:
  pack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: ${{ env.ARTIFACT_NAME }}-iac
        path: deploy/terraform/github-runner

  terraform:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: pack

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_USE_OIDC: true

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}-iac
        path: ./terraform
    
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: terraform init
      run: |
        cd ./terraform
        export
        terraform init -backend-config="key=github-runner.tfstate"

    - name: terraform validate
      run: |
        cd ./terraform
        terraform validate
    
    - name: terraform plan
      id: tfplan
      run: |
        cd ./terraform
        terraform plan

    - name: Terraform Plan Status
      if: steps.tfplan.outcome == 'failure'
      run: exit 1

    - name: terraform apply
      run: |
        cd ./terraform
        terraform apply -auto-approve

    - name: logout
      run: |
        az logout
