name: GitHub-Runner-Config

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/github-runner-config.yml'
      - 'deploy/ansible/**'

  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/github-runner-config.yml'
      - 'deploy/ansible/**'

env:
  ARTIFACT_NAME: "github-runner-config"

permissions:
  id-token: write
  contents: read

jobs:
  pack:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: ${{ env.ARTIFACT_NAME }}-ansible
        path: deploy/ansible

  ansible:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: pack

    env:
      PVT_KEY: ${{ secrets.VM_PVT_KEY }}

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}-ansible
        path: ./ansible

    - name: create key file
      run: |
        cd ./ansible
        echo $PVT_KEY | base64 -d > inventory/vm_key.pem
        chmod 400 ./inventory/vm_key.pem
       # cat ./inventory/vm_key.pem

    - name: run ansible playbook
      run: |
        cd ./ansible
        ansible-playbook -i inventory/hosts.yml playbook.yml --extra-vars "github_token=${{ secrets.MY_PAT }}"
